### ISSUE TITLE
CursorWindowAllocationException

### ISSUE THREAD

**Issue by Armen101** [InMobi/sdk-sample-code-android#35] opened 2019-05-14 07:22 UTC
com.inmobi.b.b.b.a.a (InitConfigurationDBHelper.java:248)
com.inmobi.commons.a.a.a (SdkContext.java:2170)
com.inmobi.ads.e.b.a (AdPreFetcher.java:8252)
com.inmobi.ads.e.b$4.run (AdPreFetcher.java:281)

**Comment by SwagatoMondal** [comment] 2019-05-24 07:29
Hi @Armen101 thanks for letting us know, we're already working on it. We're gonna fix the issue in the upcoming version of the SDK.

**Comment by Armen101** [comment] 2019-05-24 07:31
Thanks!  I'll wait

**Comment by lakshya21** [comment] 2019-05-29 07:16
Hey @Armen101, the issue is fixed in the latest release. You can go ahead and update the sdk with the latest version.

**Closed as completed** 2019-05-30 10:38 UTC
