### ISSUE TITLE
v9.0.2 does not fire banner load event

### ISSUE THREAD

**Issue by koush** [InMobi/sdk-sample-code-android#52] opened 2020-02-10 03:30 UTC
As title says, adding a listener to the InMobiBanner does not fire the onAdLoadSucceeded event.

Works fine in 8.x.x.

**Comment by SwagatoMondal** [comment] 2020-02-10 05:59
Hi @koush,
Can you provide us with the following details?
1. AccountID
2. PlacementID
3. Slot size

**Comment by koush** [comment] 2020-02-10 09:09
93c0667c98ec44319e7c5a6b680a3af1
300x250 or 320x50
not sure what slot size is

**Comment by SwagatoMondal** [comment] 2020-02-10 10:16
Thanks for the information, but I'm guessing 
`93c0667c98ec44319e7c5a6b680a3af1` is your **accountID**, can you at least also provide the **PlacementID**?

**Comment by koush** [comment] 2020-02-10 18:53
`1580004391025`
or 
`1580138927577`

**Comment by koush** [comment] 2020-02-10 18:54
To be clear: 
I can see in the android log that the ad was successfully retrieved, the ad loads properly, but the event itself never fires. This makes it break with mediation libraries like mopub, since it thinks the ad timed out.

Downgrading the library resolved the issue.

**Comment by SwagatoMondal** [comment] 2020-02-12 07:01
@koush Give it one more try (maybe by clearing app data while testing), it should start working now.

**Comment by SwagatoMondal** [comment] 2020-02-16 13:07
Guessing the issue is fixed for you, hence closing the issue.

**Closed as completed by SwagatoMondal** 2020-02-16 13:07 UTC
